In [32]:
import numpy as np
test=np.random.rand(10000)

### 插入排序
    插入排序的基本操作就是将一个数据插入到已经排好序的有序数据中，从而得到一个新的、个数加一的有序数据，算法适用于少量数据的排序，时间复杂度为O(n^2)。是稳定的排序方法。插入算法把要排序的数组分成两部分：第一部分包含了这个数组的所有元素，但将最后一个元素除外（让数组多一个空间才有插入的位置），而第二部分就只包含这一个元素（即待插入元素）。在第一部分排序完成后，再将这个最后元素插入到已排好序的第一部分中
    先排第一个，把第二个插入，然后在把第三个插入。

In [2]:
def insert_sort(lists):
    # 插入排序
    count = len(lists)
    for i in range(1, count):
        key = lists[i]
        j = i - 1
        while j >= 0:
            if lists[j] > key:
                lists[j + 1] = lists[j]
                lists[j] = key
            j -= 1
    return lists

In [33]:
%time insert_sort(test)

Wall time: 15 s


array([2.59103536e-05, 4.30852707e-05, 8.32045091e-05, ...,
       9.99886735e-01, 9.99895469e-01, 9.99963724e-01])

## 冒泡排序 
    它重复地走访过要排序的数列，一次比较两个元素，如果他们的顺序错误就把他们交换过来。走访数列的工作是重复地进行直到没有再需要交换，也就是说该数列已经排序完成。

In [62]:
def bubble_sort(lists):
    # 冒泡排序
    count = len(lists)
    for i in range(0, count):
        for j in range(i + 1, count):
            if lists[i] > lists[j]:
                lists[i], lists[j] = lists[j], lists[i]
    return lists

In [35]:
%time insert_sort(test)

Wall time: 8.88 s


array([2.59103536e-05, 4.30852707e-05, 8.32045091e-05, ...,
       9.99886735e-01, 9.99895469e-01, 9.99963724e-01])

### 快速排序
    通过一趟排序将要排序的数据分割成独立的两部分，其中一部分的所有数据都比另外一部分的所有数据都要小，然后再按此方法对这两部分数据分别进行快速排序，整个排序过程可以递归进行，以此达到整个数据变成有序序列。

In [64]:
def quick_sort(lists, left, right):
    # 快速排序
    if left >= right:
        return lists
    key = lists[left]
    low = left
    high = right
    while left < right:
        while left < right and lists[right] >= key:
            right -= 1
        lists[left] = lists[right]
        while left < right and lists[left] <= key:
            left += 1
        lists[right] = lists[left]
    lists[right] = key
    quick_sort(lists, low, left - 1)
    quick_sort(lists, left + 1, high)
    return lists

In [76]:
%time quick_sort(test,10,50)

Wall time: 0 ns


array([2.59103536e-05, 4.30852707e-05, 8.32045091e-05, ...,
       9.99886735e-01, 9.99895469e-01, 9.99963724e-01])

In [75]:
%time np.sort(test)

Wall time: 501 µs


array([2.59103536e-05, 4.30852707e-05, 8.32045091e-05, ...,
       9.99886735e-01, 9.99895469e-01, 9.99963724e-01])